permalink: pretty
relative_permalinks: true

#theme: jekyll-theme-midnight
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

collections:
        filters:
                permalink: "/:collection/:path/"
                output: true


just_the_docs:
        collections:
                filters:
                        name: Filters
